Traceback (most recent call last):
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/miniconda3/envs/tf2/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/miniconda3/envs/tf2/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# inspect data
ee_df = pd.DataFrame()
for ii,ee in enumerate(df_daqa_person['education_experiences']):
    if ee is None: continue
    if len(ee):
        this_ee = pd.json_normalize(ee)
        this_ee['display_name'] = df_daqa_person.iloc[ii]['display_name']
        ee_df = ee_df.append(this_ee)

# remove incomplete and remove rows with no completion dates
ee_df = ee_df[ee_df['coverage_range.date_range.date_end'] != 'incomplete']
ee_df = ee_df[~ee_df['coverage_range.date_range.date_end'].isnull()]

# remove rows with no qualification data
ee_df = ee_df[~ee_df['school.qualification'].isnull()]
ee_df = ee_df[ee_df['school.qualification'] != 'INCOMPLETE']

# remove rows with no school name
ee_df = ee_df[~ee_df['school.name'].isnull()]

# remove case of honorary doctorates
ee_df = ee_df[ee_df['school.name'] != 'QUT, UQ']

# remove redundant columns
ee_df = ee_df.drop(['school.type','coverage_range.date_range.date_start'],axis=1)
                  
# fix missing place name
ee_df.loc[ee_df['school.name'] == 'CAMBRIDGE','coverage_range.place'] = 'UK'
    
# fix anomalies
ee_df = ee_df[~ee_df.display_name.isin(['Bruce Goodsir', 'Donald Watson', 
                                        'Dorothy Brennan','Malcolm Bunzli', 
                                        'Robyn Hesse','Edward James Archibald Weller',
                                        'Lilly Addison', 'Richard Allom'])]
    
# Summary statistics
print('Summary statistics')
display(HTML(ee_df.describe().to_html()))

# # Missing data
# print('\nMissing data')
# ee_df.isnull().sum()

print(f'There are {ee_df.shape[0]} person records with education data.')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [11], line 38[0m
[1;32m     36[0m [38;5;66;03m# Summary statistics[39;00m
[1;32m     37[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mSummary statistics[39m[38;5;124m'[39m)
[0;32m---> 38[0m display([43mHTML[49m(ee_df[38;5;241m.[39mdescribe()[38;5;241m.[39mto_html()))
[1;32m     40[0m [38;5;66;03m# # Missing data[39;00m
[1;32m     41[0m [38;5;66;03m# print('\nMissing data')[39;00m
[1;32m     42[0m [38;5;66;03m# ee_df.isnull().sum()[39;00m
[1;32m     44[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mThere are [39m[38;5;132;01m{[39;00mee_df[38;5;241m.[39mshape[[38;5;241m0[39m][38;5;132;01m}[39;00m[38;5;124m person records with education data.[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'HTML' is not defined
NameError: name 'HTML' is not defined

